export enum MarcaVeiculo {
    VOLKSWAGEN = 'Volkswagen',
    FORD = 'Ford',
    CHEVROLET = 'Chevrolet',
    RENAULT = 'Renault',
    FIAT = 'Fiat',
    HONDA = 'Honda',
    TOYOTA = 'Toyota',
    NISSAN = 'Nissan',
    HYUNDAI = 'Hyundai',
    MITSUBISHI = 'Mitsubishi',
    JEEP = 'Jeep',
    KIA = 'Kia',
    PEUGEOT = 'Peugeot',
    CITROEN = 'Citroën',
    MERCEDES_BENZ = 'Mercedes-Benz',
    BMW = 'BMW',
    AUDI = 'Audi',
    VOLVO = 'Volvo',
    LAND_ROVER = 'Land Rover',
    SUBARU = 'Subaru',
    TESLA = 'Tesla',
    PORSCHE = 'Porsche',
    DODGE = 'Dodge',
    CHRYSLER = 'Chrysler',
}